# -*- coding: utf-8 -*-
"""cd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YzhAhg8eiX_TZZ3aH_tH7MxIMeRGMJLo
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

cd=pd.read_csv(r"C:\Users\ANISH SAHOO\Downloads\CAR DETAILS FROM CAR DEKHO.csv",index_col=0)

cd.head()

cd.shape

cd.info()

cd.columns

cd.describe()

cd.duplicated().value_counts()

cd.owner.unique()

cd.owner.value_counts()

sns.countplot(x=cd.owner)
plt.title('Owner Count')

cd.head(2)

cd.transmission.unique()

sns.countplot(x=cd.transmission)
plt.title('Transmission Categories Count')

cd.year.unique(),len(cd.year.unique()),cd.year.dtype

sns.countplot(x='year',data=cd,palette='viridis')
plt.title('year distribution')
plt.show()

cd.seller_type.unique()

sns.countplot(cd.seller_type)
plt.title('Seller_type Count')

cd.selling_price.unique()

cd.km_driven.unique()

cd.km_driven.value_counts()

sns.countplot(x = cd.km_driven)
plt.title('Low Range v/s High Range')

cd.head(2)

cd[['year','selling_price','km_driven']].info()

cd.head(2)

a=cd.groupby('transmission')['selling_price'].agg(pd.Series.mode)
b=cd.groupby('transmission')['km_driven'].agg(pd.Series.mode)

a

b

plt.figure(figsize=(18,10))
plt.subplots_adjust(left=0.1,
                    bottom=0.1,
                    right=0.9,
                    top=0.9,
                    wspace=0.4,
                    hspace=0.4)
plt.subplot(2,2,1)
a.plot(kind='bar',title="transmission_vs_selling_price")
plt.subplot(2,2,2)
b.plot(kind='bar',title="transmission_vs_km_driven")
plt.show()

cd.isna().sum()

def fill_nan_category(category_column):
    x=cd.groupby('year')['category_column'].agg(pd.Series.mode)
    for i,j in zip(x.index,x):
        cd.loc[cd['year']==i,category_column]=cd.loc[cd['year']==i,category_column].fillna(j)

def fill_nan_category(category_column):
    x = cd.groupby('year')[category_column].agg(
        lambda x: x.mode().iloc[0]
    )

    for i, j in zip(x.index, x):
        cd.loc[cd['year'] == i, category_column] = \
            cd.loc[cd['year'] == i, category_column].fillna(j)


fill_nan_category('selling_price')
fill_nan_category('km_driven')

cd[['selling_price', 'km_driven']].info()

cd.selling_price.unique(),cd.selling_price.isnull().count()

plt.hist(cd.selling_price,bins=10)

sns.histplot(x = cd.selling_price,data=cd,bins=10)

sns.distplot(cd.selling_price,bins=10)

cd.info()

cd.head()

cd.to_csv('cd_clean_data.csv')

plt.figure(figsize=(15,5))
plt.subplots_adjust(left=0.1,
                    bottom=0.1,
                    right=1,
                    top=0.9,
                    wspace=0.4,
                    hspace=0.4)
plt.subplot(1,2,1)
plt.title('Density Over selling_price')
sns.kdeplot(x='selling_price',data=cd)
plt.subplot(1,2,2)
sns.boxplot(y='selling_price',data=cd)
plt.title('selling_price Range')
plt.show()

Q1,Q3=np.percentile(cd.selling_price,[25,75])
IQR=Q3-Q1
lower_limit=Q1-(1.5*IQR)
upper_limit=Q3+(1.5*IQR)
print(Q1,Q3)
print('Lower Limit:',lower_limit)
print('Upper Limit:',upper_limit)

cd.selling_price.quantile([0.25,0.5,0.75])

cd.groupby('transmission').agg({'transmission':'count'}).transmission.plot(kind='pie',autopct='%1.1f%%',figsize=(5,5),shadow=True)
plt.title('Transmission percentage')
plt.show()

plt.figure(figsize=(15,8))
plt.subplots_adjust(left=0.1,
                    bottom=0.1,
                    right=1.2,
                    top=0.9,
                    wspace=0.4,
                    hspace=0.4)
hi=cd[cd['transmission']=='H'].value_counts('selling_price').reset_index()
lo=cd[cd['transmission']=='L'].value_counts('selling_price').to_frame()
plt.subplot(1,2,1)
sns.kdeplot(x = 'selling_price',data=hi).set_title('High')
plt.subplot(1,2,2)
sns.kdeplot(x = 'selling_price',data=lo).set_title('Low')
plt.suptitle('selling_price Distribution of high and low consumptions')
plt.show()

p=cd.groupby('transmission').agg({'selling_price':sum}).reset_index()
sns.barplot(x='transmission',y='selling_price',data=p)
plt.title('selling_price w.r.t transmission')
p

print(cd.columns.tolist())

seller_type = cd['seller_type'].value_counts().sort_values(ascending=False).head(50)

plt.figure(figsize=(5, 5))
sns.barplot(y=seller_type.index, x=seller_type.values)

plt.title('Most Buying Product by Customers')
plt.xlabel('Count')
plt.ylabel('Seller Type')

plt.show()

c1=cd.groupby('transmission')['selling_price'].value_counts().to_frame().rename(columns={"selling_price":'p_count'}).reset_index()
c2=cd.groupby('transmission')['km_driven'].value_counts().to_frame().rename(columns={"km_driven":'p_count'}).reset_index()
plt.subplots_adjust(left=0.1,
                    bottom=0.1,
                    right=1.2,
                    top=0.9,
                    wspace=0.4,
                    hspace=0.4)
plt.subplot(1,3,1)
sns.barplot(x='selling_price',y='count',hue='transmission',data=c1).set_title('Purchase by transmission for selling_price')
plt.subplot(1,3,2)
sns.barplot(x='km_driven',y='count',hue='transmission',data=c2).set_title('Purchase by transmission for km_driven')
plt.show()

HI=cd[cd['km_driven']==0].value_counts('selling_price').to_frame()
LO=cd[cd['km_driven']==1].value_counts('selling_price').to_frame()
plt.figure(figsize=(15,8))
plt.subplots_adjust(left=0.1,
                    bottom=0.1,
                    right=1.2,
                    top=0.9,
                    wspace=0.4,
                    hspace=0.4)
plt.subplot(1,2,1)
sns.kdeplot(x = 'selling_price',data=HI).set_title('High')
plt.subplot(1,2,2)
sns.kdeplot(x = 'selling_price',data=LO).set_title('Low')
plt.suptitle('selliing_price Distribution of High and Low customers')
plt.show()

cd.groupby('km_driven').agg({'km_driven':'count'}).km_driven.plot(kind='pie',autopct='%1.1f%%',figsize=(5,5),shadow=True)
plt.title('Customer Visits Frequently (Low v/s High)')
plt.show()

cd.head(1)

import matplotlib.pyplot as plt
import seaborn as sns

# Group data
ZX = cd.groupby(['transmission', 'km_driven'])['selling_price'].sum().reset_index()

# Seller type counts
DX = cd['seller_type'].value_counts().nlargest(10)

# Owner counts
PX = cd['owner'].value_counts().nlargest(10)

# Adjust layout
plt.subplots_adjust(
    left=0.1,
    bottom=0.1,
    right=0.95,
    top=0.9,
    wspace=0.4,
    hspace=0.4
)

# Graph 1
plt.subplot(2, 2, 1)

sns.barplot(
    x='km_driven',
    y='selling_price',
    hue='transmission',
    data=ZX
)

plt.title('Selling Price w.r.t Transmission and KM Driven')
plt.xticks(rotation=45)

# Graph 2
plt.subplot(2, 2, 3)

DX.plot(kind='bar')

plt.title('Seller Type')
plt.xlabel('Seller Type')
plt.ylabel('Number of Cars')
plt.xticks(rotation=45)

# Graph 3
plt.subplot(2, 2, 4)

PX.plot(kind='bar')

plt.title('Owner')
plt.xlabel('Owner')
plt.ylabel('Number of Cars')
plt.xticks(rotation=45)

plt.show()

# Display grouped data
ZX













